[font]
normal = { family = "Iosevka", style = "Regular" }
size = 13

[window]
padding = { x = 4, y = 4 }

[selection]
save_to_clipboard = true

[colors.primary]
background = '#202020'
foreground = "#ffffff"

[colors.normal]
black   = "#2f2f2f"
red     = "#ff3e3e"
green   = "#b0ee76"
yellow  = "#f4bf75"
blue    = "#78b6ce" # #78b6ce
magenta = "#ff73fd"
cyan    = "#91e1d2"
white   = "#fdf2f2"

[colors.bright]
black   = "#7a7a7a"
red     = "#ffb9b9"
green   = "#d0f07e"
yellow  = "#ffd7af"
blue    = "#b0dbe2"
magenta = "#ff5ce9"
cyan    = "#a4ffed"
white   = "#ffffff"
