[font]
normal = { family = "Iosevka", style = "Regular" }
size = 18

[window]
padding = { x = 4, y = 4 }

[selection]
save_to_clipboard = true

[colors.primary]
background = "#1e2022"
foreground = "#eeedde"

[colors.normal]
black   = "#303030"
red     = "#d17067"
green   = "#8cad5b"
yellow  = "#f4d381"
blue    = "#739cd9"
magenta = "#d98ac8"
cyan    = "#6CBBBF"
white   = "#d0d0bc"

[colors.bright]
black   = "#a2a2a2"
red     = "#ff9e9b"
green   = "#b8d888"
yellow  = "#E6B18E"
blue    = "#99c9ee"
magenta = "#e4abfc"
cyan    = "#91E0E4"
white   = "#d9fff4"

