[font]
normal = { family = "Iosevka", style = "Regular" }
size = 13

[window]
padding = { x = 4, y = 4 }

[selection]
save_to_clipboard = true

[colors.primary]
background = '#202020'
foreground = "#f5f3ff"

[colors.normal]
black   = "#25242d"
red     = "#eb98b5"
green   = "#b0ee76"
yellow  = "#f6c177"
blue    = "#78b6ce" # #78b6ce
magenta = "#ff73fd"
cyan    = "#91e1d2"
white   = "#e9f9e4"

[colors.bright]
black   = "#a29cc5"
red     = "#ebbcba"
green   = "#ebffce"
yellow  = "#f4e4bd"
blue    = "#9ccfd8"
magenta = "#ff5ce9"
cyan    = "#a4ffed"
white   = "#ffffff"
