[font]
normal = { family = "Iosevka", style = "Regular" }
size = 11

[window]
padding = { x = 4, y = 4 }

[selection]
save_to_clipboard = true

[colors.primary]
background = '#1e1e1e'
foreground = "#e9eadb"

[colors.normal]
black   = "#262525"
red     = "#ce4545"
green   = "#8ca356"
yellow  = "#f4bf75"
blue    = "#71aac8"
magenta = "#d98ac8"
cyan    = "#7ecfc8"
white   = "#dcead4"

[colors.bright]
black   = "#909090"
red     = "#ff7777"
green   = "#aac474"
yellow  = "#f6d573"
blue    = "#8dd8f1"
magenta = "#ea9ee0"
cyan    = "#82f0d4"
white   = "#f8f8f8"
