[font]
normal = { family = "Iosevka", style = "Regular" }
size = 11

[window]
padding = { x = 4, y = 4 }

[selection]
save_to_clipboard = true

[colors.primary]
background = '#262626'
foreground = "#e9ebd5"

[colors.normal]
black   = "#262525"
red     = "#D99898"
green   = "#8ca356"
yellow  = "#F1E4AB"
blue    = "#AFCBE3"
magenta = "#d98ac8"
cyan    = "#6CBBBF"
white   = "#dcead4"

[colors.bright]
black   = "#909090"
red     = "#D49E9E"
green   = "#aac474"
yellow  = "#E6B18E"
blue    = "#8dd8f1"
magenta = "#ea9ee0"
cyan    = "#91E0E4"
white   = "#f8f8f8"
