[font]
normal = { family = "Iosevka", style = "Regular" }
size = 11

[window]
padding = { x = 4, y = 4 }

[selection]
save_to_clipboard = true

[colors.primary]
background = '#202020'
foreground = "#e9eadb"

[colors.normal]
black   = "#25242d"
red     = "#ac4242"
green   = "#90a959"
yellow  = "#f4bf75"
blue    = "#78b6ce"
magenta = "#bd7bbc"
cyan    = "#75b5aa"
white   = "#e3ffd4"

[colors.bright]
black   = "#909090"
red     = "#ff7777"
green   = "#aac474"
yellow  = "#feca88"
blue    = "#8dd8f1"
magenta = "#ea9ee0"
cyan    = "#82f0d4"
white   = "#f8f8f8"
